### ISSUE TITLE
Web map with selectable tasks in mobile map view

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#1]
Working Web map in mobile view on Android device, from which users can:
- See available tasks
- Click on tasks, triggering a mechanism allowing them to select the task and launch ODK Collect with the appropriate project, app user, and form configured.

**Comment by krtonga** [comment]
With the merge of the `fast-api` branch, this Issue is:

Ugly implemented in the UI. 

Known issues:
- popup buttons don't fit in their dialogs, and will crash the app if clicked. 
- popups do not change to only show actions for "logged in user" who has locked a task.
- task list below the map is very rough and does not contain all information. 
- qr codes and other task detail is not yet sent to the front end.
