### ISSUE TITLE
Include task id and user details in submissions

### ISSUE THREAD

**Issue by Sujanadh** [hotosm/fmtm#1077]
## Current situation
At the moment, no information related to task_id is included in the submissions. We may need task_id in the submissions table of a project to know submissions related to specific task.

## Expected behaviour
```
[
  {
    "start": "2023-12-28T14:11:57.057+05:45",
    "end": "2023-12-28T14:13:01.690+05:45",
    "today": "2023-12-28",
    "phonenumber": null,
    "deviceid": "collect:qKQrgKKs1LrYoFoC",
    "username": null,
    "email": null,
    "instructions": null,
    "warmup": {
      "type": "Point",
      "coordinates": [
        85.3284721,
        27.7303575,
        1278.9000244140625
      ],
      .
      .
      .
      "deviceId": "collect:qKQrgKKs1LrYoFoC",
      "edits": 0,
      "formVersion": "2023-12-28T08:25:29Z"
    },
    "task_id": 1160
  }
]
```
## Or
similar form table like in odk-central for the project table. And for the task wise submissions we can open respective task form.
![Screenshot from 2024-01-02 17-17-49](https://github.com/hotosm/fmtm/assets/109404840/9541b501-d4e1-4b9c-ae0b-93f58702ee77)

```
[
    {
        "projectId": 1817,
        "xmlFormId": "1156",
        "state": "open",
        "enketoId": "ItDbHAUobNiQsGYphkwUTQusdWx7qAL",
        "enketoOnceId": "5aa95d85c80e3dfd5dc2e757e3cd0958bf6ce7deae381b85e08525aff126dc93",
        "createdAt": "2023-12-28T08:21:26.662Z",
        "updatedAt": "2023-12-28T08:25:12.361Z",
        .
        .
        .
        },
        "lastSubmission": null,
        "excelContentType": null,
        "createdBy": {
            "id": 5,
            "type": "user",
            .
            .
            .
        }
    },
    {
        "projectId": 1817,
        "xmlFormId": "1157",
        "state": "open",
        "enketoId": "uhH81szdLmXPAfjhn3yifVHbAf2pQJk",
        "enketoOnceId": "b702ba2af71507352d26f70f6a2b1496037a72e44dfe74860455b2a7a7c6b289",
        "createdAt": "2023-12-28T08:21:43.145Z",
        "updatedAt": "2023-12-28T08:25:19.842Z",
       .
       .
       .
        },
        "lastSubmission": null,
        "excelContentType": null,
        "createdBy": {
            "id": 5,
            "type": "user",
           .
           .
           .
        }
    }
]
```
Need advice on this.

**Comment by spwoodcock** [comment]
We could possibly misuse the phonenumber or email fields during qr code generation. 

I have been looking into adding the username too.

Will test and reply here on Monday 👍

**Comment by spwoodcock** [comment]
### Possible Solution

So we ideally want both the osm username and the associated task id to be linked with the submission.

It is possible to encode these values in the QRCode, then have Collect read them (we then need to test if they send to Central).

The QR code is the only link to FMTM we have once loaded into Collect, so it seems like the only way.

### Hurdle to Overcome

The only issue is that the QR codes are all generated in advance, so we can't include the osm username too.

To do that we would need to generate the QR Codes dynamically every time a user clicks on the project area, instead of all at once.
It's doable, but needs a fair bit of updating.

What do you think @Sujanadh ?
