### ISSUE TITLE
The icon of the organization is cropped in the project card

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1104]
**Describe the bug**
The icon of the organization is cropped in the project card.

**To Reproduce**

1. Go to Explore Projects
2. View the project card

**Expected behavior**
The complete logo of the organization needs to be viewed and not cropped.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/108750444/93a51262-cef8-4217-8acc-d711ec3d3d4e)
![image](https://github.com/hotosm/fmtm/assets/108750444/ca690cc2-3fda-4b4d-a30f-cd5fed11be03)

**Comment by NSUWAL123** [comment]
@manjitapandey, @susmina94 di
Update: if complete logo is supposed to be visible then some of the logos including this one will be too small  & unclear like this one. 
![image](https://github.com/hotosm/fmtm/assets/81785002/9b4ad024-9f61-4def-8777-1dfd9841b41a)
![image](https://github.com/hotosm/fmtm/assets/81785002/2a14f320-af14-4ccd-ac52-05151112a324)

The logo in manage organization page is visible & clear since its width is 150px. But in this project card it is not possible to make it 150px as it would be too large.

**Comment by spwoodcock** [comment]
Very good point - we should look at how Tasking Manager has solved this.

Ideas:
- Ask the user to upload a logo of equal dimensions (most orgs have a favicon logo, and then a larger image logo).
- Upload two separate logos for display in different pages (not ideal).
- There is probably a better solution.

**Comment by NSUWAL123** [comment]
@spwoodcock, the tasking manager also displays the org logo like this: 
![image](https://github.com/hotosm/fmtm/assets/81785002/58d7ace2-25a5-40b3-92cf-152581d5a093)

So shall we display org logo like this??

**Comment by spwoodcock** [comment]
Yes ideally then - looks like the width of the icon is dynamic depending on the logo.

Can we have a standard width container element that doesn't change (for consistent UI), but the icon inside can change width?
