### ISSUE TITLE
Tasks splitting fails when we use other category except buildings

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1279]
**Describe the bug**
When i try to split tasks using task splitting algorithm for other categories except buildings. For linear features like highways and aterways, It shows task generation fails and shows 500 error at network panel

**To Reproduce**

1. Go to 'create project 
2. Click on 'highways as categories
3. Generate osm data extracts
4. try splitting tasks using algorithm
5. See error

**Expected behavior**
The tasks should be splitted for linear features too.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/1807ba84-b304-4c64-8464-99def4207d4c)

**Comment by spwoodcock** [comment]
Is this for any category other than buildings, or just for linestring features?

If it's only linestrings that fail, please update the issue title to reflect this 🙏

**Comment by manjitapandey** [comment]
I couldn't confirm about it then. The reason was I was unable to find category having point or polygon that time. However, Now it is confirmed it is not just about linear features but also about all the category except buildings.

**Comment by spwoodcock** [comment]
I just saw the AOI you have above & it makes sense that splitting fails.

The issue is there are only buildings present in the AOI (no other OSM feature type), and the buildings are not intersected by any lines such as roads, rivers, railways, airstrips due to the small AOI size.

Either we need to update fmtm-splitter to handle these cases more gracefully (with a better error message), or display a better error message on FMTM if we encounter this case.

**Comment by manjitapandey** [comment]
@spwoodcock i don't think Its due to the AOI i created, I encountered the same issue for other AOIs having more road network too.

**Comment by spwoodcock** [comment]
Can you add the AOIs that fail here please, as they are useful for debugging purposes. 

We may shift this issue to fmtm-splitter at some point, as it's likely related to the splitting algo.

**Comment by spwoodcock** [comment]
FYI
**Failures due to config**: amenities, camping, cemeteries, wastedisposal, waterpoints
**Removed**: education, nature, places

I'm sure the failures are to do with either osm-fieldwork YAML parsing, or JSON output for execQuery.
I removed them, but amenties, cemeteries, wastedisposal, waterpoints would probably be useful to add back in.
