### ISSUE TITLE
unable to see feature extract on map of detail submission page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1368]
**Describe the bug**
when i view individual submissions in detail submission page by clicking on eye button. I am unable to see the exact building mapped on map. 

**To Reproduce**

1. Go to 'submission table page'
2. Click on 'eye button of any submission to open submission detail page'
3. Scroll down to 'map section'

**Expected behavior**
the building extract should be visible in the map with by default zoomed to proper building level.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/01871d30-ca1c-42dc-b899-13aef551df58)

**Comment by NSUWAL123** [comment]
It's because the xLocation which contains the building's lineString is coming under `select_feature` key where previously it came under the xLocation of `all` key. This issue can be addressed after confirming if the building's lineString always comes under the select_feature key or not. Currently the odk-centra-naxa is not working due to which I also cannot view previous project's submission's.
