### ISSUE TITLE
unable to see username and task status on task activity.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1399]
**Describe the bug**
I am unable to see the username who changed the status of task and the state to which the task status is changed in task activity list of project page. 

**To Reproduce**

1. Go to 'Project page'
2. Click on 'task activities'

**Expected behavior**
The task activities should show who changed the task status and to which task status. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/1b008c43-36ff-4509-a9f3-0308c1539376)

**Comment by spwoodcock** [comment]
Related to discussion in #1393

I think the issues should he combined into:

'Allow another form of authentication outside of OSM'

The specific issue here is because we disabled auth to allow mappers to lock tasks.

The issue in 1393 is that auth has been reenabled on the lock task endpoint, so users that are not logged in cannot change the task state. 

The solution is to create another form of simplified auth that mappers can use, outside of OSM.

As discussed in the other thread, we could do this via temporary tokens (either through email, or just generated on the user providing their name)
