### ISSUE TITLE
Users can't see basemap beneath shaded task area

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1632]
**Describe the bug**

![image](https://github.com/hotosm/fmtm/assets/78538841/80c88815-22a6-4d14-801a-a32687b6665a)

![image](https://github.com/hotosm/fmtm/assets/78538841/4ed2bddb-04c1-44ad-ad1e-382818ef113a)

- When a basemap is loaded it's not easy to actually see it.
- The task areas have a grey shading with transparency that obscures the basemap.
- Particularly annoying when geolocation is enabled too. 

**Expected behavior**

- Perhaps clicking the task area should make the shading completely transparent?
- This would allow users to more easily map.

**Comment by manjitapandey** [comment]
This can be something we can do to improvise user's experience but i wonder how interested the users would be to view basemaps clearly. 
Also what would be the case if user selects entity instead of whole task. Will we be removing the transparency then too?? If so how will the user understand the status of tasks?
