### ISSUE TITLE
unable to update task status

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1657]
**Describe the bug**
I am unable to update the task status to locked for mapping. This issue can be replicated on dev server. The console panel shows 500 error on `https://api.dev.fmtm.hotosm.org/tasks/10889/new-status/1?project_id=40` post API

**To Reproduce**

1. Go to 'any project'
2. Click on 'a task you want to mark as locked for mapping'

**Expected behavior**
The task should be locked for mapping. 

**Screenshots**
![image](https://github.com/user-attachments/assets/64034b47-257a-4d24-a35d-088dc09f92e6)

**Additional context**

**Comment by spwoodcock** [comment]
Oh I had that issue when working on the mapper frontend - I thought it was due to my db schema changes. 

It was a simple fix if I remember - I think it was the indexing of the returned db object

**Comment by Sujanadh** [comment]
working on it

**Comment by spwoodcock** [comment]
I just rebased the mapper frontend branch to latest development - seems the issue isn't what I thought it was.

It's just the change to the return type of the mapper role:

![image](https://github.com/user-attachments/assets/5f75775a-640e-4358-827d-402a9aeb8b5a)

A db object is returned instead of a pydantic model now

**Comment by spwoodcock** [comment]
This is a bigger issue, as described above. Multiple endpoints don't work as a result, including project creation.

Need... tests... arrrgghhhh 
![giphy](https://github.com/user-attachments/assets/b5494d03-0e1e-4ce1-b97a-1c42fd94c308)
