### ISSUE TITLE
Dummy roles populated in project

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1678]
By default there is a list of duplicated dummy role assignment accessible under `manage project` section. Is this the expected behaviour? @spwoodcock @manjitapandey 

![image](https://github.com/user-attachments/assets/9f5d35a4-d115-4ebe-9dc2-9d557f61e13c)

**Comment by NSUWAL123** [comment]
- https://github.com/hotosm/fmtm/issues/1679#issuecomment-2238050189

No @ramyaragupathy, this is not expected behaviour. At first, we thought we were going to complete this feature and included/made `USERS` tab visible. But now as there was a blocking issue on the backend this feature was on hold. I have hidden the `USERS` tab yesterday. 

And @spwoodcock, if possible can cherrypick the change to the `main` branch?

**Comment by spwoodcock** [comment]
Oh nice work @NSUWAL123 !

Currently on my phone, so if you get a chance to send me the commit hash to cherry pick I will do it first thing Monday 👍

I'm sure I can find it on Monday otherwise!

**Comment by NSUWAL123** [comment]
Commit hash:
7ac1cd9a6f73c47ed8fd37c08436f810baecdf85

**Comment by spwoodcock** [comment]
Done 👍 

This is cherry-picked into `main`, meaning it is on production (not on staging)

**Comment by spwoodcock** [comment]
Actually, the deploy failed: https://github.com/hotosm/fmtm/actions/runs/10039537524/job/27743712821
Probably a fix that is done in `development` that I missed.

It would be easier to just wait for next release until this is hidden in the UI.
If it's high priority / urgent, I could spend the time to debug the test issues on `main`.

**Comment by manjitapandey** [comment]
I guess we are good to go to merge this issue along with other on our regular release schedule. The UI has been hidden on dev server for now.
