### ISSUE TITLE
Unable to pick and assign user roles in project

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1679]
Attempting to pick a registered user for role assignment. However nothing happens in the frontend.
I expect:
* a list of usernames that can be selected for role assignment
* and `assign role` operation updates access to the project and list it immediately in the table below

@spwoodcock @Sujanadh @NSUWAL123 @manjitapandey  

![fmtm-role-assignment](https://github.com/user-attachments/assets/a7fb50e4-2b38-45b6-9dc5-5b0c14b8af72)

**Comment by NSUWAL123** [comment]
This feature of assigning and inviting users is not completed yet. Only UI slicing has been done. Yesterday I hid the users tab so users wouldn't get confused with this. 
However, I don't remember but there was a blocking issue on the backend side related to the email of the user. And that's why this feature was on hold right @spwoodcock, @Sujanadh?

**Comment by manjitapandey** [comment]
I guess We should temporarily hide the UI for now until the feature is completed from backend.

**Comment by NSUWAL123** [comment]
It has been done and already merged yesterday @manjitapandey.
- https://github.com/hotosm/fmtm/pull/1669
