### ISSUE TITLE
Reduce the opacity of the task overlay with satellite base

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1681]
Would be great to reduce the project layer opacity when a satellite/TMS layers is chosen for basemap. It is hard to decipher features while on field.

cc @spwoodcock @NSUWAL123 @manjitapandey 
@Sujanadh 
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/7021cd4a-9e08-4ac7-b5d8-8a47c35d8082">

**Comment by spwoodcock** [comment]
Dup of https://github.com/hotosm/fmtm/issues/1632

**Comment by manjitapandey** [comment]
The opacity is reduced but not made transparent. Do this much of opacity work or we have to make it completely transparent? 
@spwoodcock , @ramyaragupathy

**Comment by spwoodcock** [comment]
Looks ok to me!

**Comment by manjitapandey** [comment]
This issue is not fixed on staging.
![image](https://github.com/user-attachments/assets/6e108f70-299a-4ee8-b821-31d6228ad568)
cc: @spwoodcock , @NSUWAL123

**Comment by NSUWAL123** [comment]
I think the current level of opacity is needed to distinguish the status of the task.  The quality of the TMS layer used in the project is horrible. Although making layer is transparent, the buildings are not seen due to very poor quality. 

![image](https://github.com/user-attachments/assets/4338a39e-8c18-4577-acc6-832012cd3cae)
![image](https://github.com/user-attachments/assets/89715144-8d82-44b0-b2f8-bdaafca8e61f)

CC: @spwoodcock, @manjitapandey
