### ISSUE TITLE
Small issues with form questions on mandatory XLSForm fields

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1897]
**Issue 1**

In the XLSForm, I can select a geometry fine:

![image](https://github.com/user-attachments/assets/7fa8f693-4079-4df2-ac7f-ecb8704d4962)

But then it asks me another question after to select a building:

![image](https://github.com/user-attachments/assets/926f3d8e-c747-4789-9b2c-406a5ecea998)

I think related to recent additions to the form logic (about additional entities)

**Issue 2**

- If the user selects 'building does not exist', it would be nice if they could take a photo of the area.
  - Currently the form skips the photo question in this scenario.
- Perhaps we move the photo question outside the verification section as a standalone question, and always ask this question (photos are always useful)?
  - Other options to achieve this?

**Comment by manjitapandey** [comment]
Issue 1: I can confirm this is due to additional entities being introduced and can be replicated when no optional field is added. 
Expected behavior: Only show the question if additional features are added during project creation.

Issue 2: It would be nice but we have to make this question optional since, most users on those case are not sure what to click if there is no feature.
