### ISSUE TITLE
Modify form title in settings of xlsform

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#19]
currently form_id and version are modified, need to add the title column (C2 in Rob's form templates) to that.

**Comment by robsavoye** [comment]
This turned out to be really easy. I looked into using pandas to read the spreadsheet, but it was not an optimal solution. As I have parsed many XML files before using xmltodict, that was used to change the version and task name, and the data extract file name. The advantage here is one of performance. Rather than editing the XLSForm source file, and running xls2xform for each task, this only requires conversion once.

**Comment by robsavoye** [comment]
As of #4783baf7, this now works.
