### ISSUE TITLE
Issues/ enhancement on mapper frontend

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1901]
**Describe the bug**

- Open ODK button can't redirect to odk. It needs manual loading of projects by downloading the QR code. 
- Users aren't clear what to do after downloading QR. They aren't inform they need to load QR code on odk.
- The buildings colour is currently green which provides the sense that features are already mapped. 
- ~Users aren't able to login through mapper frontend. If mapper frontend URL is shared, they need to get back to react frontend and log in and get back to mapper frontend.~ #1890
- There is no way to get back to react frontend from mapper frontend. 

**To Reproduce**

1. Go to 'project's page'
2. Replace project from url to mapnow
3. Go to mapper frontend through navigation

**Expected behavior**

- [x] We can remove Open ODK button from mapper frontend or we need to open odk collect and load project automatically through clicking the button if that's technically possible.
- [x] Also add clear instruction that they need to load project on odk collect.
- [x] Change the colour of not mapped in feature. We can change the mapped feature colour to green.
- [x] Add option on hamburger menu to get back to react frontend or explore project page along with other features. 
- [x] Remove play and stop mapping buttons from mapper frontend.

**Screenshots**
![Screenshot_2024-11-19-13-36-29-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9e853f8c-d209-4977-8722-d6e67b2e0f60)

![Screenshot_2024-11-19-13-40-57-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f8a3fa31-d3af-4983-b47e-db78aed114f9)

**Additional context**

**Comment by spwoodcock** [comment]
For the QR Code tab, could we update the next to say:

'Scan this QR code in ODK Collect from another users phone, or download and import it manually (i)'

The (i) should be a little information icon to expand.
Clicking it should open this gif as a small popup:
![signal-2024-11-19-08-45-32-675-ezgif.com-resize.gif](https://github.com/user-attachments/assets/9ff644ae-a505-4d2f-a0f0-ad85f4086f57)

**Comment by NSUWAL123** [comment]
Currently `changing color of the entity based on its mapping status` is not possible.

Reason: 
The Geojson properties of the feature extract contain `osm_id` as a unique identifier whereas the entity status API (`/shape?table=odk_entities`) contains `entity_id` as a unique identifier. Since there's no common attribute to connect the entities with their respective statuses, it's not possible. 

Screenshot:
Feature extract geojson
![Image](https://github.com/user-attachments/assets/109384ef-d60d-4c5b-b557-a09052fc6386)

Status API response
![Image](https://github.com/user-attachments/assets/d9d74f7f-ed41-4510-b456-c2b671b39a7b)

Solution: 
Maybe the feature extract properties should contain `entity_id` or the status API should contain `osm_id`.

**Comment by spwoodcock** [comment]
If you were to call `/entities/statusus` for the project at first load, would this be enough info to link the entities to the extract geoms?

https://github.com/hotosm/fmtm/blob/development/src%2Fbackend%2Fapp%2Fprojects%2Fproject_routes.py#L192

It should include both entity id and osm id in the response
