### ISSUE TITLE
Geolocation should be automatic on mapper frontend

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1909]
**Describe the bug**

- We avoided making geolocation automatic on the management frontend, as people only viewing the project wouldn't want this.
- The mapper frontend is specific to mapping, and the user will almost always want to geolocate.
- Current UX isn't great, where the user is expected to click a button - it's not intuitive like other map apps.

**Solution**

- Automatically start the geolocation when the mapnow page is loaded.

**Comment by manjitapandey** [comment]
When the mapnow page is loaded, the geolocation is on by default if I turn on my location beforehand. But when location is off, the chrome browser doesn't ask for the access rather shows the error message saying geolocation is denied. 
I don't think this should be expected. Can we do anything that browser ask for permission instead of error message without asking? ![Image](https://github.com/user-attachments/assets/9b49361d-cc4c-4f76-8a4d-1f9940f7f773)

**Comment by NSUWAL123** [comment]
There are two cases when the user device location is turned off: 
1. Turning geolocation on via button click (implemented in management frontend)
If the user accesses the website for the first time and hasn't touched the permissions of the website, then the permission popup is shown. If the user has already declined the permission request prior, then geolocation denied popup will be shown.
![Image](https://github.com/user-attachments/assets/a01bad62-a51f-476f-9a79-065088277686)

2. Automatic geolocation on (mapper frontend)
Here since we automatically trigger the geolocation status to be turned on, due to security measures implemented by browsers, the permission popup will not be shown and the geolocation denied popup will be shown by the browsers by default although they are new users.

I think it's not possible to show the permission popup instead of an error. But we have to research the workarounds if there's any possibility.

**Comment by spwoodcock** [comment]
That's some good info - we can look into it 👍

Is the defined popup a behaviour we can't change? Or could we change that from an alert to a toast error message?

**Comment by spwoodcock** [comment]
You are completely right about the web app limitations on getting geolocation on first load!

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API

Also see best practices here (interesting!)

https://developer.chrome.com/docs/lighthouse/best-practices/geolocation-on-start

I'm also not 100% sure that we can 'remember' the users answer for requesting geolocation on the next load either 😅

This is pretty much the main limitation we have using a PWA vs a native app!

## Conclusion

Anyway, the conclusion to this is that we may need to revert this behaviour (so sorry @NSUWAL123 🙏).

We need a clear button to trigger the location permission request and load geolocation.

We probably need to add this info to any docs, asking the user to geolocate before they start mapping. 

The Google Maps approach UI / UX is good here, as a reference we should probably emulate 

![Screenshot_20241213-181141.png](https://github.com/user-attachments/assets/93c641d4-0229-4801-a03f-e3ac3f898a6a)

**Comment by manjitapandey** [comment]
Next Actions:

- [ ] @NSUWAL123 to add more clear button for location similar to google maps. 
- [ ] @manjitapandey to document the instruction to clearly state you need to enable geolocation before start mapping
