### ISSUE TITLE
Issues on mapper frontend on offline mode

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1940]
**Describe the bug**
The button for downloading and loading tiles on mapper frontend is missing

**To Reproduce**

1. Go to 'mapper frontend page'
2. Click on 'offline mode'
3. Choose the basemap 

**Expected behavior**
The button should be visible for downloading the tiles as well as visualising the tiles on mapper frontend

**Screenshots**
![Image](https://github.com/user-attachments/assets/7c8d2e7f-f0e8-4929-9036-a3f283d32c53)

**Comment by spwoodcock** [comment]
Which project was this for?

I can see the buttons on this project: https://dev.fmtm.hotosm.org/mapnow/35
Just checking if you can too?

**Comment by manjitapandey** [comment]
I can't see the buttons on #35 of dev server (Naxa Demo project).
They are still not visible on my device

**Comment by spwoodcock** [comment]
Confirmed on mobile - this is a mobile only bug - will look into it!

**Comment by spwoodcock** [comment]
@NSUWAL123 if you could possibly look at this and do a sanity check, it would be really appreciated 🙏 

I haven't really had a chance to check it thoroughly, but it's quite an important thing to fix.

Such a weird error 😅 The buttons are visible on desktop, but not mobile, I think it's to do with the CSS classes, but on first look I couldn't work it out!

**Comment by NSUWAL123** [comment]
Sure!

**Comment by NSUWAL123** [comment]
The problem is different event target support for different browsers.
Mozilla Firefox seems to support `target` and `originalTarget`, but Chrome only supports `target`.
As `originalTarget` was used there to retrieve the URL id, chromium browsers couldn't access it.

Now the issue is the PMTile showed on the base maps list but didn't load due to s3 URL error.

Chrome
![Image](https://github.com/user-attachments/assets/3882fb89-ed36-4cfe-9e8f-03a884eca055)

Mozilla Firefox
![Image](https://github.com/user-attachments/assets/c08c394d-194b-4f89-a2f6-ae88958e8e22)

**Comment by spwoodcock** [comment]
Wow, really great debugging!

Indefinitely learnt something new 😁

I can look into the s3 URL issue

**Comment by spwoodcock** [comment]
Reminder to me: check the URLs on the basemap uploads

**Comment by spwoodcock** [comment]
Nice!

Perhaps the URL error was because @NSUWAL123 is using a project that was made prior to the basemap S3 upload changes?

There is a migration script that can be used to upload all the basemaps for your local projects to local S3:

```bash
docker compose exec api bash
python migrations/upload-basemaps-to-s3.py
```
