### ISSUE TITLE
Split by Sqaure can results to some tiny tasks.

### ISSUE THREAD

**Issue by Sujanadh** [hotosm/fmtm#1960]
**Is your feature request related to a problem? Please describe.**
Currently our split by square can results to tiny tasks which is not good. It will only increase the tasks number and records in table.

![Image](https://github.com/user-attachments/assets/17bcc2f0-2959-4f49-99ac-02483c38f46f)

**Describe the solution you'd like**
Merge them to nearset task if they fall under category of minimun threshold for example: less than the 20 % of task area (square generated). 

**Describe alternatives you've considered**
User changes the parameter until they get desired tasks area. 

What would be best approach here? 
@manjitapandey @ramyaragupathy  @spwoodcock

**Comment by spwoodcock** [comment]
Agree! Merging into neighbouring squares is the way.

The approach in drone tm is good

https://github.com/hotosm/drone-tm/blob/1b7c81ded92fbf9417cd48e3ad32f043ddce7f0f/src/backend/app/tasks/task_splitter.py#L124

Although if it could be in SQL / PostGIS instead it would be even nicer!

Also I'm sure they have a reason, but I cant quite work out why they used that threshold calculation. If it makes sense to you, then use it,  but otherwise a 35% threshold could be appropriate

**Comment by Sujanadh** [comment]
To use SQL/Postgis, we won't have tasks geom stored in db while splitting. For that, we might need to create a temporary table and do all the operations using PostGIS. And, I think it is still good to use temporary temp and do the operations.

**Comment by Sujanadh** [comment]
@spwoodcock  One question: should we also consider tasks with no features?

**Comment by Sujanadh** [comment]
So shall we fetch extracts and avoid tasks without features or only if users provide custom extracts?

**Comment by spwoodcock** [comment]
If the user provides an extract, remove squares with no features.

If the user doesn't provide an extract, simply split by square (don't account for features) 👍
