### ISSUE TITLE
Inconsistency in taskID on project details page and mapper's page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1982]
**Describe the bug**
The taskID on project details page on management frontend is different than the taskID of same task on mapper view. On project details page, the taskId start from 1 whereas the number is large on mapper's page

**To Reproduce**

1. Go to 'project details page of any project'
2. Click on 'any task to see task ID'
3. Click on start mapping to go to mapper's page
4. Click on same task to see different project ID.
5. See error

**Expected behavior**
The taskId should be consistent on each page

**Screenshots**
![Image](https://github.com/user-attachments/assets/6d018ee7-d345-4aab-9070-82d53925b9e0)
![Image](https://github.com/user-attachments/assets/130fc163-acff-42b3-9634-25680b369018)

**Additional context**

**Comment by NSUWAL123** [comment]
@spwoodcock in the activities panel, we need to replace `task id` with `task index` on the UI. So we probably need to add a `task_index` column in the table? 

![Image](https://github.com/user-attachments/assets/4579fae1-3f78-499b-ab9b-cbfbb405888e)
![Image](https://github.com/user-attachments/assets/fae13fba-65b7-4482-9ea5-c7b5656e9c8d)

**Comment by spwoodcock** [comment]
In the submission table for the react frontend?
That's probably a good idea too.

Updating the activities panel on the mapper frontend is all needed to as you say - just updating the number is fine I think

**Comment by NSUWAL123** [comment]
No. In the activities section in the mapper frontend, we show the task id in the UI. To ensure consistency over the UI we should also display the task index in the activities section. Currently, only task id is being returned from electric SQL since it's querying from the `task_events` table (database table ) where there is no task index column.

**Comment by spwoodcock** [comment]
Oh sorry, I get you! I don't think we should display the task id to the user. Only the index 👍

If we could remove the id reference entirely itbwouod be great, but I think we need it for calling the API and adding new events

**Comment by NSUWAL123** [comment]
Yeah for the visible part of UI, we should use index, but we need id for API calls.

**Comment by spwoodcock** [comment]
> @spwoodcock in the activities panel, we need to replace `task id` with `task index` on the UI. So we probably need to add a `task_index` column in the table? 
> 
> ![Image](https://github.com/user-attachments/assets/4579fae1-3f78-499b-ab9b-cbfbb405888e)
> ![Image](https://github.com/user-attachments/assets/fae13fba-65b7-4482-9ea5-c7b5656e9c8d)
> 

Oh you mean we might need to add task index to the task events table?

I'm reluctant to do that, as its a computed field anyway, rather than a user input of real value.

I understand the issue now, as the task index is typically calculated on the backend for the tasks API response, but we are using electric.

Based on the response from electric, could we not find the max and min task ids, set to an internal value in the store, then calculate the range (max-min) to set the task index values based on the task ids? Or something similar to this

**Comment by NSUWAL123** [comment]
Then I'll make a list of objects mapping the task id with its index the {id: index}[]. Both id and index are returned in the /project/:id/minimal API. Then access the index where needed.
