### ISSUE TITLE
Broken UI: Dropdown not showing any options

### ISSUE THREAD

**Issue by suthamakes** [hotosm/fmtm#1991]
In the FMTM website when I am trying to create a new project, the field where I have to select "Organization Name" is not working and is empty.

**To Reproduce**

1. Go to 'https://fmtm.hotosm.org/'
2. Click on '+CREATE NEW PROJECT'
3. Scroll down to 'Organization Name' drop down option
4. See error that it isn't showing any organization's name.

**Screenshots**
![Image](https://github.com/user-attachments/assets/ac5c2876-1f52-407e-83e1-d23238451cc1)
![Image](https://github.com/user-attachments/assets/7e935a7b-9d60-441d-bb89-7ba601e46536)

**Comment by spwoodcock** [comment]
Thank you @suthamakes for the report!

I have a feeling the underlying issue is because of a small issue with the login logic. The UI shows you as logged in still, but you may not in fact be logged in properly.

We can fix the logic to correctly clear the login state if its invalid. (@NSUWAL123)

In the meantime, could you log out and log in again, then try again?

**Comment by NSUWAL123** [comment]
I can't confirm this now as the OSM is in read-only mode due to an outage. So, I will check on this issue later.

**Comment by suthamakes** [comment]
@spwoodcock is the OSM OAuth currently down?

**Comment by NSUWAL123** [comment]
Yes @suthamakes OSM is in read-only mode due to their network outage. Their api's arent working

**Comment by spwoodcock** [comment]
Sorry about that! Project creation isn't possible without OSM 😅 (mapping is though)

Its just one of those unpredictable and unlucky situations. OSM has had very good uptime for years, but will be down until about Wednesday due to some major issues with their ISP. Details here https://community.openstreetmap.org/t/openstreetmap-org-currently-offline-operations-team-are-working-to-restore-15-december-2024-updated/122930/9

We will accelarate efforts to allow other login methods such as Google, to prevent this affecting FMTM if it happens again in future 🙏

**Comment by NSUWAL123** [comment]
I guess this issue is solved
