### ISSUE TITLE
Fix auto-deplyment

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#331]
Every time I approve a PR, I get an error message like this one:
https://github.com/hotosm/fmtm/actions/runs/4627198864

**Comment by Ndacyayisenga-droid** [comment]
> Every time I approve a PR, I get an error message like this one: https://github.com/hotosm/fmtm/actions/runs/4627198864

Hey @robsavoye 

Can you assign this so I can take on the investigation

**Comment by Ndacyayisenga-droid** [comment]
> Every time I approve a PR, I get an error message like this one: https://github.com/hotosm/fmtm/actions/runs/4627198864

@robsavoye Does the same happen when a PR is merged to the main branch?
I thought about this because our workflow file suggests main branch. Anyways I am just trying to think out loud, I don't know whether the workflow reads development as main when triggered with a PR!

https://github.com/hotosm/fmtm/blob/5977ff06049b56596fb6677e2d09528929124ce0/.github/workflows/prod_deploy.yml#L5

**Comment by robsavoye** [comment]
For the last few weeks, all approved PRs have been going into the development branch not main.

**Comment by spwoodcock** [comment]
I think the issue could have actually been the comment on the same line, making it invalid.
Attempted fix in PR - let me know if you still get errors.

**Comment by spwoodcock** [comment]
Realised this was actually fixed already, I'm not going crazy...

I saw a lot of fails in the Actions tab, but it's actually from the `feat-submission` branch, which was made before the previous fix.
@nrjadkry you can rebase to `development` if you want to stop the action failures 👍 

On a side note: turns out automatically closing issues by referencing in a PR only works if the PR is to the **default branch**.
(i.e. in the PR, something like: "Fixes #9999")
Perhaps we should consider making `development` the default branch:
1. To prevent people making PRs to `main`.
2. To allow referencing and closing issues in PRs.

What do you think @robsavoye? Can you foresee any issues in having it as the default branch?
