### ISSUE TITLE
Replace geojson features with flatgeobuf

### ISSUE THREAD

**Issue by nrjadkry** [hotosm/fmtm#381]
@robsavoye We are thinking about switching from geojson to vectortile so that it can handle large size of map layers be it buildings or the project or task boundaries. What do you think about this?

**EDIT** see discussions below. We should use vector tiles for baselayers, but the boundary overlays should be a vector format such as flatgeobuf.

**Comment by robsavoye** [comment]
a vectortile isn't useful for clipping, as it contains zoom levels, which we don't care about. For both the project AOI and the task boundaries, GeoJson is fine.

**Comment by spwoodcock** [comment]
Perhaps a cloud native vector format such as flatgeobuf or Geoparquet could be considered instead?

Anything that can utilise HTTP Range requests would be much more efficient than loading the entire geojson file (if file size is a concern).

But where exactly are we looking to optimise? Aren't task boundaries stored directly in the database?

**Comment by robsavoye** [comment]
I have been able to make vector mbtiles of OSM data, the only problem is they have no styling, so this would be all black and white. I can use mapnik to add styling though, just haven't gotten around to it yet.

**Comment by spwoodcock** [comment]
Performance will be terrible for large projects using GeoJSON.

I would suggest we try using PMTiles - they are perfect for this use case.
They are basically just MBTiles, but with better optimisation for the web.
(MBTiles are SQLite based, made to work offline. PMTiles use HTTP RANGE requests to only access the data they need on demand).

During project creation we could generate a PMTiles output of all boundaries, and host it on S3.
More info on generating PMTiles here: https://github.com/hotosm/raw-data-api/issues/136
The S3 URL is stored in the database for direct access by the frontend (this will be fast).

## Prerequisite
- This will probably be after the tech team meetup, as it needs S3 hosted on AWS or Azure.

## Additional Considerations
- We need to factor in styling too. It should be similar for MBTiles and PMTiles output.

**Comment by varun2948** [comment]
Sounds great @spwoodcock as we still face the issue with the GEOJSON when the project area is larger. 
Can we get the feature properties of the layer in the PMTiles or geoparquet?

**Comment by spwoodcock** [comment]
PMTiles are just a vector tile, so you can query in the same way.

Examples:
OpenLayers tile queries: https://openlayers.org/en/latest/examples/vector-tile-info.html
OpenLayers tile selection: https://openlayers.org/en/latest/examples/vector-tile-selection.html

Note: GeoParquet is a very cool format, but vector tiles may be more suited to this use case (plus client support isn't as good yet).

**Comment by spwoodcock** [comment]
The only issue we have is actually creating the tiles - we need to write some code for that.

Two options (in order of preference):

1. Use tippecanoe to generate Postgis DB data --> PMTiles.
There is a good example using node here - we can do the same in Python: https://qiita.com/T-ubu/items/3855054e394e3e7518fe#practice-6-reading-data-from-postgresqlpostgis-data-using-nodejs-using-cursor-modify-the-result-and-export-as-vector-tile-pmtiles

2. Create MBTiles as with the code we have currently, then bundle the `go-pmtiles` binary in the FMTM image to convert MBTiles --> PMTiles.

Both of these options should probably be part of another repo, then imported in. We should have a think about which one @robsavoye. I would assume `osm-rawdata` is a good choice, to reuse this in export tool etc.

**Comment by spwoodcock** [comment]
Example of PMTile generation for raw-data-api by Kshitij (using tippecanoe): https://github.com/hotosm/raw-data-api/pull/151

It's becoming clearer to me that we should use FMTM for most of the map functionality, including navigation (instead of ODKCollect). Let ODKCollect stick to it's wheelhouse: forms.

**Some thoughts for a potential solution to solve both the offline basemap and large geojson issues**:

1. Project is created with task boundaries.
2. Two PMTile outputs are generated on S3 inside directory structure like `/bucket/<project_id>/FILES`:
  - `basemap.pmtiles`: underlying tile layer (osm, satellite, drone).
  - `boundaries.pmtiles`: project boundary, task boundaries, and OSM data extract within each task boundary.
3. When user has connectivity, they can just use the (bandwidth efficient, cached) PMTiles without issue.
4. When a user clicks to download files for offline usage on a specific task:
  - The tiles in the task AOI are extracted from the `.pmtiles` using Python [aiopmtiles](https://github.com/developmentseed/aiopmtiles) (this could be a Lambda function, or a FastAPI function).
  - Tiles are packaged up as `.mbtiles` for use in either FMTM mobile app offline, or in ODKCollect (via [filepicker idea in the ODK forum](https://forum.getodk.org/t/provide-a-way-to-get-mbtiles-to-collect-without-having-to-connect-to-a-computer/42206/9))
5. The user goes mapping in their task area with FMTM for navigation, selecting a building.
6. The QR code is generated and imported into ODKCollect (this step will be improved in the future with a PR to ODKCollect for direct App Links).
