### ISSUE TITLE
Integrate Celery for background tasks.

### ISSUE THREAD

**Issue by nrjadkry** [hotosm/fmtm#693]
As we work on integrating MBTiles with ODK Collect, we need to handle extracting tiles in the background. While FastAPI has its own BackgroundTasks, it might not work well for large tasks. That's why I am thinking about using Celery. Celery can help us manage large tasks more effectively. It splits the work into smaller pieces and handles them efficiently

**Comment by spwoodcock** [comment]
Agreed that Celery is probably our best bet here.

We can use it with Redis, as we don't need anything more heavyweight like RabbitMQ.

A project I used to work on had a good implementation for reference: https://github.com/sjacorg/bayanat/blob/main/docker-compose.yml

## What we need

- A separate dependencies group called celery with extra deps that may be needed:

`pdm add -G celery some-other-dependency`

- The fmtm backend dockerfile to extract out this dependencies group into a separate requirements file. An extra stage should then be made to install these requirements and set the CMD to `celery -A ...`.

- Add the celery image and redis to the docker compose stack. Celery uses the same dockerfile as fmtm but the target is the stage mentioned above.

The extra dependencies group may not be needed for now if the background tasks only use code in osm-fieldwork.

**Comment by robsavoye** [comment]
I think Celery may be overkill. There are two kinds of threading in applications. One is you fire up a background thread, and just let it run til completion, for example how submissions get downloaded now. There is no communication needed with the spawning application.

The other type is where all the threads have to communicate, so you need a message passing layer. That's what Celery would supply, but I don't think we need it. For basemap production, it's already multi-threaded internally. For other background tasks, if there is no need to communication, then I wouldn't bother with Celery.

**Comment by spwoodcock** [comment]
I agree it's good to keep it as simple as possible.

Celery is great and has some advantages. For one, if the task takes a long time and the server has an outage (or a container restarts) then it should resume without issue.

But if this is one of the few tasks we need to run over a long time & it's not critical it has a 100% success rate, then you are probably right that introducing celery is unecessary.

We could run as a FastAPI background task. The only thing we should make sure is that the workflow can be resumed if it fails. If the downloading doesn't complete, then the user can trigger it again to complete it.

**Comment by robsavoye** [comment]
downloading tiles is worse than that as it's uncommon to get network errors from the server with the imagery. For complete coverage I often have to run the download several times, or you get blank tiles at various zoom levels. So yes, I'd fire up downloading, and all we care about is when it's done. Since basemapper doesn't download anything that is already cached, resuming after any outage is also easy. To resume, just start the download again, and it'll pick up where it left off.

Celery looks great if we needed any inter-task communication, but for this particular thing, it's more than we need. Basemapper itself already uses a thread pool to download multiple tiles in parallel. OpenLayer supports a TMS feed, we could even view the tiles as they populate the AOI if we want to get fancy.

I usually start at zoom level 8, which is pretty far back, but can be used to navigate. Zoom level 18 is tolerable for a basemap in Collect, when possible I'll add level 19, which is where the imagery maxes out anyway.

**Comment by spwoodcock** [comment]
Having tiles populate during download would be very cool.

Let's implement with Background Tasks first then and see how it goes.
